version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: HtmlAgilityPack
    versions:
    - 1.11.31
    - 1.11.32
  - dependency-name: Microsoft.AppCenter.Analytics
    versions:
    - 4.2.0
  - dependency-name: Microsoft.AppCenter.Crashes
    versions:
    - 4.2.0
